version: 0.2

phases:
  build:
    commands:
      - echo Build Starting on `date`
      - ./gradlew clean
      - ./gradlew build
  post_build:
    commands:
      - echo $(basename ./build/libs/*.jar)
      - pwd
      - cp build/libs/user-service-application.jar ../user-service-application.jar

artifacts:
  files:
    - user-service-application.jar