version: '3.8'

services:
  app:
    image: rpattem/user-auth-image:latest
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:mysql://db:3306/mydatabase
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=rootpassword
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=mydatabase
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: